### PR TITLE
scalatestplus to test scope

### PR DESCRIPTION
**Pull request by ittaiz**

### CODE REVIEW

**Comment by thesamet** [comment]
Thank you, Sir!

**Comment by ittaiz** [comment]
Happy to help. Thank you for the swift handling.
Do you cut versions for all of scalapb together?
I'd love to get this change but if it's for everything together I'll wait for StructUtils to be merged first

**Comment by thesamet** [comment]
protoc-bridge is cut independently. I can do this before structutils gets in.

**Comment by ittaiz** [comment]
That would be great.
We’re on an older version and I’m upgrading us to the latest to flush out issues (to make upgrading to the version with StructUtils easy) and I’d love to have the upgrade without test dependencies :)

**Comment by ittaiz** [comment]
@thesamet we'll probably do one upgrade of both changes so I'd just appreciate it if you could also releasse protoc-bridge before/with the struct utils change. Thanks!

**Pull request merged**
