### PR TITLE
Windows tests

### PR DESCRIPTION
**Pull request by augi**
As preparation for solving #9, I made the tests working on Windows.

### CODE REVIEW

**Comment by augi** [comment]
The check is failing because `Regex` object doesn't have `quote` method in Scala 2.10.x. What is your prefer solution? Are you willing to drop support of Scala 2.10.x, or should I use `Pattern.quote` method instead?

**Comment by thesamet** [comment]
Let's use `Pattern.quote`, we need to continue to support sbt 0.13.x.

**Comment by augi** [comment]
Ok, migrated to `Pattern.quote`. Please note that this change also contains the `project/build.properties` file so let's wait for #11 and #10.

**Comment by augi** [comment]
I rebased my branch so it's ready to be merged now.

**Pull request merged**
